### ISSUE TITLE
aria-controls to beef up accessibility

### ISSUE THREAD

**Issue by TheAce74** [cyntler/hamburger-react#69]
I've been using this package for a while and I've got no complaints; it's awesome 🔥 

Would it be possible to add a **controls** prop to the hamburgers? It would provide more context to screen readers about the actual item the hamburger is controlling.

I've been working around this with this hack:
```javascript
  useEffect(() => {
    const menu = document.querySelector(".hamburger-react");
    menu.setAttribute("aria-controls", "primary-navigation");
  }, []);
```

If it is possible, can I be assigned to the task?

**Comment by cyntler** [comment]
@TheAce74 Yes! I assigned the task to you!

**Comment by TheAce74** [comment]
@cyntler Thank you, I'll start working on it as soon as I can

**Comment by TheAce74** [comment]
I just added this enhancement, refer to #71 for more info
