### ISSUE TITLE
Support React 19

### ISSUE THREAD

**Issue by MosheSchnitzler** [cyntler/hamburger-react#75]
Can we please add support to React Canary (19)?

This package only supports react 18 and lower.
![image](https://github.com/user-attachments/assets/7791583d-9351-4df1-9621-d840d2ffbaf1)

Thank you

**Comment by Elsass1** [comment]
That's something that I would love too.

**Comment by kristianka** [comment]
This would be great since React 19 is now stable!

**Comment by RyelBanfield** [comment]
Is this just a matter of updating the dep to 19 and adding it under peerDeps? Or what else would be required here?

**Comment by Gavin-Hofer** [comment]
I tried it with react 19 and it works fine, so I think the peerDeps just need to be updated.

**Comment by Gavin-Hofer** [comment]
Until the package is updated, you can add an override in your package.json to allow use with react 19:

```json
"overrides": {
    "hamburger-react": {
      "react": "^19"
    }
  }
 ```

**Comment by cyntler** [comment]
@MosheSchnitzler @Gavin-Hofer That's ready: https://github.com/cyntler/hamburger-react/releases/tag/v2.5.2

**Comment by MosheSchnitzler** [comment]
> [@MosheSchnitzler](https://github.com/MosheSchnitzler) [@Gavin-Hofer](https://github.com/Gavin-Hofer) That's ready: https://github.com/cyntler/hamburger-react/releases/tag/v2.5.2

Thank you!!
