### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by estherfinsen** [cyntler/hamburger-react#76]
When i try to install the package "hamburger-react": "^2.5.1", does not show up in my package.json, even tho the terminal gives me this "MacBook-Air-8:finsens.dk Esther$ npm install hamburger-react

up to date, audited 38 packages in 1s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities"

The hamburger menu works fine on my website but when i try to deploy the site on vercel i get this error(photo). 
<img width="1280" alt="Skærmbillede 2024-12-12 kl  14 38 12" src="https://github.com/user-attachments/assets/cc662ba4-3f58-4429-b0be-e2e06d0bf497" />

I have tried to write "hamburger-react": "^2.5.1" directly in my package.json file. does not work.
I have made a new project and tried on that, and tried everything that chatgpt suggets... please help me, this is my final exam that should be handed in December 19th.

**Comment by estherfinsen** [comment]
Hi, thanks for your answer!! 
I do use next.js yes, and i have used the hamburger menu, with no problems before (last time was around may/june). 
-I did just try to uninstall, and install the way you suggested. Did not work (see photos).


<img width="1280" alt="Skærmbillede 2024-12-16 kl  14 01 14" src="https://github.com/user-attachments/assets/534f422e-08dc-442a-963c-f0ca15fdc564" />
<img width="561" alt="Skærmbillede 2024-12-16 kl  14 01 32" src="https://github.com/user-attachments/assets/d68df7d1-7d6a-4887-88ca-942fc6675c46" />
<img width="661" alt="Skærmbillede 2024-12-16 kl  14 03 19" src="https://github.com/user-attachments/assets/89920b7a-68f5-4266-8315-924ab9d8f27a" />

**Comment by kristianka** [comment]
The problem most likely is that React 19 (which Nect.js 15.1.0 is based on) isn't supported yet, see #75

**Comment by estherfinsen** [comment]
Thank you for the respons @kristianka. Is there any way to solve this? 
I do have other problems with my package.json file, and npm run dev function i terminal, so i do think that maybe adds to the problem? 
<img width="1280" alt="Skærmbillede 2024-12-17 kl  13 52 54" src="https://github.com/user-attachments/assets/5bbc7a4f-46a6-45ea-a874-e33007bbf0d2" />

**Comment by RyelBanfield** [comment]
@e

> Hi, thanks for your answer!! I do use next.js yes, and i have used the hamburger menu, with no problems before (last time was around may/june). -I did just try to uninstall, and install the way you suggested. Did not work (see photos).
> 
> <img alt="Skærmbillede 2024-12-16 kl 14 01 14" width="1280" src="https://private-user-images.githubusercontent.com/124664722/396104601-534f422e-08dc-442a-963c-f0ca15fdc564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDY3MDcsIm5iZiI6MTczNDQ0NjQwNywicGF0aCI6Ii8xMjQ2NjQ3MjIvMzk2MTA0NjAxLTUzNGY0MjJlLTA4ZGMtNDQyYS05NjNjLWYwY2ExNWZkYzU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNDQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWY1ZmZhOGJmMDQ4MThlY2Y0MmJhNDY0NTQyM2VhZDcxNzY3YjQyNzljN2I2ZjAwYjM4OTcxYjYzM2NmZmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lDIgkI7mkJeFACrGUg030b9qFWqpRb6GFR_lw6lLv4w"> <img alt="Skærmbillede 2024-12-16 kl 14 01 32" width="561" src="https://private-user-images.githubusercontent.com/124664722/396104675-d68df7d1-7d6a-4887-88ca-942fc6675c46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDY3MDcsIm5iZiI6MTczNDQ0NjQwNywicGF0aCI6Ii8xMjQ2NjQ3MjIvMzk2MTA0Njc1LWQ2OGRmN2QxLTdkNmEtNDg4Ny04OGNhLTk0MmZjNjY3NWM0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNDQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTIxMTU5OTNiMDUyODdlZGM0YzE5MmYyMjdhMzhiMjkyMTI3YmQyYzQ2NzRmMmE0MTA4NmFlMWI4ZTAyYjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c1B-Hk43tTuFJtcyc5fcMqc1yFm6YuQdxGkr6yGb43A"> <img alt="Skærmbillede 2024-12-16 kl 14 03 19" width="661" src="https://private-user-images.githubusercontent.com/124664722/396105201-89920b7a-68f5-4266-8315-924ab9d8f27a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDY3MDcsIm5iZiI6MTczNDQ0NjQwNywicGF0aCI6Ii8xMjQ2NjQ3MjIvMzk2MTA1MjAxLTg5OTIwYjdhLTY4ZjUtNDI2Ni04MzE1LTkyNGFiOWQ4ZjI3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNDQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDI4ZWJkZWNiMWY4ZjBlMTI3N2U2NTQ4ZGU2NDRhM2RlYmUwYzcyNDE1YjhhNjdlODE4ZGRhZDYxYzljYTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Erq6wOPCA903nWujHQiuGh10QnjSgRF1ApyvGTyYPbw">

Hey! I don't see hamburger-react in your package.json. Are you running the install command while inside of the repo?

**Comment by RyelBanfield** [comment]
> Hi, thanks for your answer!! I do use next.js yes, and i have used the hamburger menu, with no problems before (last time was around may/june). -I did just try to uninstall, and install the way you suggested. Did not work (see photos).
> 
> <img alt="Skærmbillede 2024-12-16 kl 14 01 14" width="1280" src="https://private-user-images.githubusercontent.com/124664722/396104601-534f422e-08dc-442a-963c-f0ca15fdc564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDY5NDYsIm5iZiI6MTczNDQ0NjY0NiwicGF0aCI6Ii8xMjQ2NjQ3MjIvMzk2MTA0NjAxLTUzNGY0MjJlLTA4ZGMtNDQyYS05NjNjLWYwY2ExNWZkYzU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNDQ0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTU3YjU0ZDczY2VmMDJiY2E4NTJlNmQxZjNiNDMzMzgyMGU4NWM4YTllYWY1NTQ5YmQ5MmQ4MDYzMDgzYjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iugvb2y5iT0Jy_F9pfMUdpUuuz9Blb-EUw4HuRBHI2k"> <img alt="Skærmbillede 2024-12-16 kl 14 01 32" width="561" src="https://private-user-images.githubusercontent.com/124664722/396104675-d68df7d1-7d6a-4887-88ca-942fc6675c46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDY5NDYsIm5iZiI6MTczNDQ0NjY0NiwicGF0aCI6Ii8xMjQ2NjQ3MjIvMzk2MTA0Njc1LWQ2OGRmN2QxLTdkNmEtNDg4Ny04OGNhLTk0MmZjNjY3NWM0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNDQ0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTAwNTNhNjNkOTM5ZjQwZTY4ODY1MzY1NTU0ZGRjOWRmODFjOThiOTkzOTIwNzQxYTE1OGMyNDE1Yzg0Y2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c5u1X3DvOpegDLAFDoG82cf2ejPQbCeGm1OqyYIAUF8"> <img alt="Skærmbillede 2024-12-16 kl 14 03 19" width="661" src="https://private-user-images.githubusercontent.com/124664722/396105201-89920b7a-68f5-4266-8315-924ab9d8f27a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDY5NDYsIm5iZiI6MTczNDQ0NjY0NiwicGF0aCI6Ii8xMjQ2NjQ3MjIvMzk2MTA1MjAxLTg5OTIwYjdhLTY4ZjUtNDI2Ni04MzE1LTkyNGFiOWQ4ZjI3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNDQ0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTQ0NzQwMzgzOGJiOWYyNGU5OWI1YjYzYTVjMTViN2FjZTUwY2Q1Yjk0NDYwZTYzNDRiZTcxMDQ0ZjFjYzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WyWOos4l3zVFwB-CkvfreLsiaM5rh7P0bWIYqEVqlac">

Hey! I don't see the hamburger-react package in your package.json. Are you running the command in the right folder?

**Comment by estherfinsen** [comment]
Yes, thats my issue. The burgermenu works well on localhost, but i cant deploy vercel, because the package is not added in package.json. 

Sorry, I'm not sure what the right folder means? 
![image](https://github.com/user-attachments/assets/d7ba2ad5-e7e7-42ed-b33e-06598bb43886)

**Comment by RyelBanfield** [comment]
@estherfinsen okay so when you run that npm command, I see right before it says Ether$ but it should be saying something like Ether$/my-next-project. You need to run that command inside of your project.

**Comment by estherfinsen** [comment]
Thank you. ive just run command to get react react 18.2.0 instead. installed the hamburger menu again, that NOW SHOWS in my package.json. But i still get this message when i try to deploy :
<img width="1280" alt="Skærmbillede 2024-12-17 kl  16 13 56" src="https://github.com/user-attachments/assets/a7e8c6d2-1cf1-411c-981c-d7fcd3eb3669" />

**Comment by RyelBanfield** [comment]
@estherfinsen  Can you share your updated package.json?

**Comment by estherfinsen** [comment]
<img width="1280" alt="Skærmbillede 2024-12-17 kl  16 20 59" src="https://github.com/user-attachments/assets/2bc7fb4a-6caf-428f-b8ac-5b56f031ff4f" />

**Comment by RyelBanfield** [comment]
@estherfinsen that looks good. So you pushed this update to vercel and you're getting the same error? Could you share the lastest vercel error?

**Comment by estherfinsen** [comment]
Hi, i just got some help from my classmate, who figured it out! Thank you all for your time and help. :)

**Comment by kristianka** [comment]
What was the issue

**Comment by estherfinsen** [comment]
i needed a vercel.json file with 

{
  "installCommand": "npm install --legacy-peer-deps"
}
